### ISSUE TITLE
Improve data viewing

### ISSUE THREAD

**Issue by tdudgeon** [InformaticsMatters/mini-apps-data-tier-ui#287]
1. Allow to view a wider range of files and datasets (some just say "There are no actions available for this file.")
2. Allow to view datasets
3. Provide a "View in ..." option allowing the user to choose what type of viewer. e.g. Popup viewer or new browser tab. In future we will have external viewers that can be used for some types e.g. Pose Viewer
4. Provide some way to limit contents that are shown for very big files

_(more details to follow)_

**Comment by OliverDudgeon** [comment]
I think we should handle viewing files on new pages:

- Datasets: `/dataset/{id}/{version}`
- Files: `/file/{path}`

In each case we should only parse the first few MBs of the file to display. So we truncate the file and show a button below to *download* the whole file (save dialog not load the rest into the UI).

In each file / dataset modal we will have a *view* section with buttons to open different viewers. Of course we will just have a in browser text viewer route but we will also want some files to open directly in a new tab (html, images, pdfs, JSON, etc).

**Comment by ag-m2ms** [comment]
Should the new pages be implemented as a modal window (like the one implemented currently for project files) or should it be a page like the datasets page?
If the first, what should be the default action of the close button in case a user opens the URL directly in a fresh tab? If they were redirected there from an action from the app, you can pop the previous page from the history. If he gets there from a fresh tab, there's an issue since there are no pages in the history stack. We could probably push a default page in case the history is empty.
If the latter, how is the page supposed to look? Should it have the same navbar as the rest of the application? I suppose there should be a place for a 'Back' button to return to a page from where you came from. I suppose there will be the same issue as the one mentioned above.
And since both of the pages access the same download API which needs a `file_id`, wouldn't it make more sense to have one page? I suppose having two can be handy in case one of the pages is accessed from a fresh tab and you would want to redirect the user back to datasets or project files depending on it.
For the file display limit I suppose we can adjust the current API route which restreams the file to cut it after certain amount of bytes have been transferred. There might be an issue, however, that some characters consists of more bytes and cutting them in half might display a weird symbol instead. I don't think that such characters appear often but I think it should be kept in mind just in case. In any case, we need to create a custom stream pipe, which might be a bit difficult but should be doable. I am not sure if there's a better way to stop the download from client side.

**Comment by OliverDudgeon** [comment]
Each a new NextJS page which always opens in a new tab

**Comment by OliverDudgeon** [comment]
The page can just be a <Paper /> component for now but I guess we want to model the viewer on how GitHub does it:
![image](https://user-images.githubusercontent.com/22367286/140310109-caf494d1-921b-4d21-a3b9-c994d9b0ac1b.png)

**Comment by OliverDudgeon** [comment]
It could be the same page but the functionality for datasets and files might diverge

**Comment by OliverDudgeon** [comment]
Yes I think the API route would be the best place to truncate the stream. I agree there's a problem here with regards to the encoding of the files. @tdudgeon I really do think we need to handle file encoding if we want to handle viewing files.

**Comment by OliverDudgeon** [comment]
The `file` command does determine this information. I think it's what Git uses. Could this be used on the API?
```sh
100000.csv:                                   ASCII text
16-25-1000.smi:                               ASCII text
Mpro-x0387-x0072-3hop-best1-top1000.sdf.gz:   gzip compressed data, last modified: Wed Jul 29 15:44:15 2020, from Unix, original size modulo 2^32 3893723
Mpro-x0387-x0072-stage1-best1-top1000.sdf.gz: gzip compressed data, last modified: Wed Jul 29 15:51:53 2020, from Unix, original size modulo 2^32 3802362
Mpro-x0387-x0072-stage2-best1-top1000.sdf.gz: gzip compressed data, last modified: Wed Jul 29 15:52:33 2020, from Unix, original size modulo 2^32 3199728
Mpro-x0387-x0387-3hop-best1-top1000.sdf.gz:   gzip compressed data, last modified: Tue Jul 28 13:55:56 2020, from Unix, original size modulo 2^32 3518323
Mpro-x0387-x0387-stage1-best1-top1000.sdf.gz: gzip compressed data, last modified: Wed Jul 29 15:54:07 2020, from Unix, original size modulo 2^32 3612678
Mpro-x0387-x0387-stage2-best1-top1000.sdf.gz: gzip compressed data, last modified: Wed Jul 29 17:23:34 2020, from Unix, original size modulo 2^32 3732804
ScoreGalaxyGen3Ligands-best-500.sdf:          ASCII text
ScoreGalaxyGen3Ligands-best-5000.sdf:         ASCII text
ScoreGalaxyGen3Ligands-best-filtered.sdf:     ASCII text
candidates-100.sdf:                           ASCII text
dhfr-ligand.mol:                              ASCII text
dhfr-receptor-ph7.pdb:                        ASCII text
poses++.sdf:                                  ASCII text
poses++.sdf.txt:                              Little-endian UTF-16 Unicode text
poses.sdf:                                    ASCII text
poses.sdf.gz:                                 gzip compressed data, was "poses.sdf", last modified: Tue Jun  2 16:03:00 2020, from Unix, original size modulo 2^32 494418
protein.pdb:                                  ASCII text
protein.pdb.gz:                               gzip compressed data, was "protein.pdb", last modified: Tue Jun  2 16:04:20 2020, from Unix, original size modulo 2^32 191981
smina.tgz:                                    gzip compressed data, from Unix, original size modulo 2^32 727040
```

**Comment by alanbchristie** [comment]
Is `ASCII text` sufficiently discriminating?

If Tim thinks this is acceptable then it saves a lot of work but I worry he is expecting more than `ASCII text`. After all the content of `.csv` is not the same as a `.mol` or a `.pbd file.

Do we ant more than `ASCII text`?

An, if this is the case, why does the DM need to do anything? Why not download the file and figure it out yourself?

**Comment by OliverDudgeon** [comment]
The extension/mime-type + encoding from this should be sufficient to display a file and it's viewer options?

**Comment by alanbchristie** [comment]
...also this relies on the file being sufficiently 'intact' in order for `file` to work. By using the file content (and not its extension) there's a race-condition in that a file might exist (in name) but have insufficient content for `file` to work.

Using types and extensions is more _reliable_?

**Comment by tdudgeon** [comment]
Nearly all the text files we will have will be plain text. No funny characters.
So I don't see any major problems for now if we just assume the text files are plain `us-ascii`.

There are some rare exceptions, such as a SDF being in a unusual characterset so that the field values can contain Japanese characters. So in the longer term it would be useful to try to determine the charactrerset and send it along in the file/dataset description (and header when fetching the file?), and it might be useful to allow the user to change the characterset used in a viewer if the one used is not right. But I don't see this as a priority now. That said, as Ollie spotted using `file -i` does seem to give the info we need, so adding the characterset might be quite simple.

**Comment by OliverDudgeon** [comment]
So to display files for now, we just display the first 1 MB of data and leave a link to download the rest?

**Comment by tdudgeon** [comment]
Yes, something along those lines.
